#!/usr/bin/env sh

# Includes 'utils' only for standalone (direct call)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]; then
  . ../../utils
fi

log "Flatpak setup and apps install"

  # https://fostips.com/remove-flatpak-apps-free-up-disk/
  #flatpak list --app
  #flatpak list --runtime
  #flatpak uninstall --delete-data ...
  #flatpak uninstall --unused
  #flatpak uninstall --all --delete-data

  # Issues? Try:
  # flatpak repair --user
  
execute() {
  #https://docs.flatpak.org/en/latest/using-flatpak.html
  #https://flatpak.org/setup/Solus
  #https://discourse.flathub.org/t/flatpak-run-error-no-remote-refs-found-similar-to-flathub/6204
  #flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
  #flatpak remote-add --user --if-not-exists elementary https://flatpak.elementary.io/repo.flatpakrepo

  #flatpak uninstall --noninteractive --unused # --delete-data
  flatpak update
  # https://flathub.org/appse
  
  # https://github.com/mjakeman/extension-manager
  GNOME_EXTENSIONS_TOOLS=(org.gnome.Extensions com.mattjakeman.ExtensionManager com.github.tchx84.Flatseal) 
  install_flatpak_apps "${GNOME_EXTENSIONS_TOOLS[@]}"

  BROWSERS_GOOGLE=(com.google.Chrome com.google.ChromeDev) 
  install_flatpak_apps "${BROWSERS_GOOGLE[@]}"

  BROWSERS_MICROSOFT=(com.microsoft.Edge com.microsoft.EdgeDev) 
  install_flatpak_apps "${BROWSERS_MICROSOFT[@]}"

  DEV_CONTAINERS=(io.podman_desktop.podman_desktop com.github.marhkb.Pods com.github.sdv43.whaler) 
  install_flatpak_apps "${DEV_CONTAINERS[@]}"
  
  # https://community.clearlinux.org/t/fail-to-install-vscode/6920/4
  #DEV_TOOLS=(com.github.muriloventuroso.easyssh com.getpostman.Postman com.visualstudio.code org.sqlitebrowser.sqlitebrowser com.github.alecaddd.sequeler com.github.artemanufrij.regextester com.sublimemerge.App com.github.mdh34.quickdocs)
  #install_flatpak_apps "${DEV_TOOLS[@]}"
  
  DEV_CREATIVE=(org.processing.processingide)
  install_flatpak_apps "${DEV_CREATIVE[@]}"

  DEV_GIT=(org.gnome.gitg)
  install_flatpak_apps "${DEV_GIT[@]}"

  GRAPHICS=(org.flameshot.Flameshot org.gimp.GIMP nl.hjdskes.gcolor3 org.inkscape.Inkscape)
  install_flatpak_apps "${GRAPHICS[@]}"
  
  # https://www.internet-radio.com/
  # partyvibe https://www.internet-radio.com/station/pvc-psytrance/ http://www.partyviberadio.com:8010/listen.pls?sid=1&t=.mp3

  MULTIMEDIA=(de.haeckerfelix.Shortwave)
  install_flatpak_apps "${MULTIMEDIA[@]}"

  SYSTEM_TOOLS=(dev.edfloreshz.CosmicTweaks org.gnome.FontManager org.gnome.gedit )
  install_flatpak_apps "${SYSTEM_TOOLS[@]}"
  
  #This flatpak does not have write access to ~/.local/share/applications and ~/.local/share/icons, so it cannot install or uninstall PWAs.
  #https://discourse.flathub.org/t/installing-pwas-flatpak-has-no-write-access/6859
  mkdir $HOME/.local/share/icons
  flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.google.Chrome
  flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.google.ChromeDev
}

execute

