#!/usr/bin/env sh
echo setup-system-fish

# Includes setup-utilities only for standalone (directly calling)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]
then
. ./setup-utilities
fi

# May require to log out and back in

# Interesting readings:
# https://unix.stackexchange.com/questions/38175/difference-between-login-shell-and-non-login-shell/46856#46856

# https://www.cyberciti.biz/faq/change-my-default-shell-in-linux-using-chsh/
execute() {
  SHELL_CURRENT=`echo $SHELL`

  if [[ ! $SHELL_CURRENT =~ fish ]]; then   	
  	echo -e "Current SHELL is $SHELL_CURRENT"

    # https://blog.liang2.tw/posts/2017/01/without-chsh/
    if fish -c 'echo "Test fish running" >/dev/null' ; then
      chsh -s fish maxdevjs
    else
      echo "Failed to launch fish shell. Go check its installation!"
      echo "Fall back to default shell $SHELL_CURRENT ..."
    fi
  fi
}

execute

