#!/usr/bin/env sh

if [ $0 ]; then
  . ./utils
fi

DIR=$PWD

bin() {
  create_dir $HOME/.local/bin
  git clone https://github.com/maxdevjs/scripts $HOME/.local/scripts
}

execute() {
  bin
  . ./00-config/setup
  cd $DIR
  . ./01-dotfiles/setup
  cd $DIR
  . ./02-system-install-apps/setup
  cd ../../../
  . ./03-post-config/setup
  
  log "Installation done! Restart and then install flatpak apps"
  log "Now restart the 💻"
  log "Then change shell to Fish and install Flatpak apps"
}

execute

