#!/usr/bin/env sh
echo setup-dev-docker

# Includes setup-utilities only for standalone (directly calling)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]; then
  . ../../utils
else
  cd DE/gnome
  DIR=$PWD
fi

log "Docker"

#TODO: refactor. Install to step 02
function setup () {
  if ! command_exists docker; then
    #sudo swupd bundle-add containers-basic docker-compose
    #PACKAGES_DOCKER=(containers-basic docker-compose)
    #install_packages "${PACKAGES_DOCKER[@]}"
    #sudo eopkg install -y -c system.devel #>/dev/null 2>&1
    # TODO: this is Solus centered now
    # https://help.getsol.us/docs/user/software/development/containers/#docker
    sudo eopkg install docker docker-compose
    # https://www.docker.com/products/docker-desktop/
    # https://docs.docker.com/desktop/install/linux-install/
    # sudo swupd bundle-add qemu-guest-additions
  
    # AppArmor
    # https://docs.docker.com/engine/install/binaries/
        
    # https://docs.docker.com/engine/install/linux-postinstall/
    # Manage Docker as a non-root user
    # https://github.com/docker/kitematic/issues/2528
    # https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
    # https://stackoverflow.com/questions/49434650/how-to-add-a-user-to-a-group-without-logout-login-bash-script
    # https://superuser.com/questions/272061/reload-a-linux-users-group-assignments-without-logging-out#comment1036933_609141
    getent group docker || sudo groupadd docker
    # TODO: apparently eopkg does everything but this:
    sudo usermod -aG docker $USER
    newgrp docker #&& exec sudo su -l $USER
    
    # https://stackoverflow.com/a/51362528
    sudo chmod 666 /var/run/docker.sock

    sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
    sudo chmod g+rwx "$HOME/.docker" -R
    
    docker run hello-world

    # In case: https://discuss.getsol.us/d/3157-docker-not-running/3
    #sudo rm -rf /var/lib/docker/overlay
    
  fi
  
  if [ systemctl status docker.service | grep disabled ]
  then
    # https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot
    sudo systemctl enable docker.service
		sudo systemctl enable containerd.service
		
		sudo systemctl start docker.service
		sudo systemctl start containerd.service
	fi
}

setup
