#!/usr/bin/env sh
# Includes 'utils' only for standalone (direct call)
# use of this script (otherwise the script is called from setup
# and the import is not necessary)
if [ $0 ]; then
  . ../../../utils
else
  cd WM/Hyprland
  DIR=$PWD
fi

log "Installing Hyprland"

execute() {
  echo hyprcursor hyprgraphics hypridle hyprlock hyprland hyprpaper hyprland-qutils hyprutils
}

execute
